models/CaseDataEntry.py
from sqlalchemy import Column, Integer, String, TIMESTAMP
from .Base import db

class CaseDataEntry(db.Model):
    __tablename__ = 'cases_ac'

    id = Column(Integer, primary_key=True)
    cases_region = Column(Integer)
    cases_city = Column(Integer)
    deaths = Column(Integer)
    recovered = Column(Integer)
    timestamp = Column(TIMESTAMP, unique=True)
    alsdorf = Column(Integer)
    baesweiler = Column(Integer)
    eschweiler = Column(Integer)
    herzogenrath = Column(Integer)
    monschau = Column(Integer)
    roetgen = Column(Integer)
    simmerath = Column(Integer)
    stolberg = Column(Integer)
    wuerselen = Column(Integer)
    not_associated = Column(Integer)

views/CaseDataEntry.py
from datetime import datetime
from flask import render_template, Blueprint, request, url_for, flash, redirect
from sqlalchemy import asc
import pandas as pd

from models.Base import db
from helper.debug_helper import flash_on_dev
from helper.page_parser import fetch_and_parse_page_data, parse_data
from models.CaseDataEntry import CaseDataEntry

case_data = Blueprint("case_data", __name__)
db_session = db.session

@case_data.route('/cases')
def cases():
    query = db_session.query(CaseDataEntry)
    case_data_entries = query.order_by(asc(CaseDataEntry.timestamp)).all()
    columns = [col.name for col in case_data_entries[0].__table__.columns]

    return render_template("CaseDataEntry/index.html", entries=case_data_entries, columns=columns)


@case_data.route('/cases/add/csv', methods=['GET', 'POST'])
def add_csv():
    if request.method == 'GET':
        return render_template('CaseDataEntry/add_csv.html')
    else:
        if request.files and request.files['file']:
            # TODO: rather unsafe. Never trust user input
            file_contents = request.files['file']
            df = pd.read_csv(
                file_contents,
                delimiter=';',
                parse_dates=["Date"],
                dayfirst=True,
            )

            try:
                entries = []
                for index, row in df.iterrows():
                    entry = CaseDataEntry(
                        cases_region=row["Cases (Region)"],
                        cases_city=row["Cases (City)"],
                        deaths=row["Deaths"],
                        recovered=row["Recovered"],
                        timestamp=row["Date"],
                        alsdorf=row["Alsdorf"],
                        baesweiler=row["Baesweiler"],
                        eschweiler=row["Eschweiler"],
                        herzogenrath=row["Herzogenrath"],
                        monschau=row["Monschau"],
                        roetgen=row["Roetgen"],
                        simmerath=row["Simmerath"],
                        stolberg=row["Stolberg"],
                        wuerselen=row["Wuerselen"]
                    )
                    entries.append(entry)

                db_session.add_all(entries)
                db_session.commit()

                flash("Success", "success")
                return render_template("simple_text.html", html="Import successfull."), 201

            except Exception as e:
                message = f"Data import was not successful. Something went wrong. Please try again."
                flash(message, "error")
                flash_on_dev(e, "error")
                return render_template("simple_text.html", text=message), 500

        flash("Oooops. There went something wrong. Please try again.", 500)
        return redirect("case_data.add_csv"), 500


@case_data.route('/cases/add', methods=['GET', 'POST'])
def add():
    if request.method == 'POST':
        if request.form:
            try:
                entry = CaseDataEntry(
                    cases_region=request.form["cases_reg"],
                    cases_city=request.form["cases_city"],
                    deaths=request.form["deceased"],
                    recovered=request.form["recovered"],
                    timestamp=datetime.fromisoformat(f"{request.form['date']}T{request.form['time']}"),
                    alsdorf=request.form["alsdorf"],
                    baesweiler=request.form["baesweiler"],
                    eschweiler=request.form["eschweiler"],
                    herzogenrath=request.form["herzogenrath"],
                    monschau=request.form["monschau"],
                    roetgen=request.form["roetgen"],
                    simmerath=request.form["simmerath"],
                    stolberg=request.form["stolberg"],
                    wuerselen=request.form["wuerselen"],
                    not_associated=request.form["not_associated"]
                )
                session = db_session()
                session.add(entry)
                session.commit()

                flash("Data successfully added.")

                return render_template("simple_text.html", text=f"Data entry successfully added."), 201

            except Exception as e:
                flash("An error occurred!", "error")
                flash_on_dev(e, "error")

                return render_template("simple_text.html", text=f"Could not add entry. Please try again!",
                                       back_to=(url_for("case_data.add"), "Back to data entry")), 500

        flash("Error. You did not enter any or invalid data. Please try again.", "error")
        return redirect('case_data.add'), 400
    else:
        return render_template("CaseDataEntry/add.html", form_fields=CaseDataEntry.metadata, now=datetime.now())


@case_data.route("/cases/fetch")
def fetch_from_page():
    results = fetch_and_parse_page_data()

    if results is None or len(results) == 0:
        flash("No data received")
        return render_template("simple_text.html", text="No data found")

    return render_template("CaseDataEntry/add_from_external_page.html", data=results)

@case_data.route("/cases/text", methods=["GET", "POST"])
def fetch_via_text():
    if request.method == "GET":
        return render_template("CaseDataEntry/add_via_text.html")

    else:
        if request.form:
            try:
                date_text, content_text = request.form["text"].split("\n", maxsplit=1)
                
                result = parse_data(date_text, content_text)
                print(result)

                flash("Data successfully added.")

                return render_template("CaseDataEntry/add_from_external_page.html", data=[result])

            except Exception as e:
                flash("An error occurred!", "error")
                flash_on_dev(e, "error")

                return render_template("simple_text.html", text=f"Could not add entry. Please try again!",
                                       back_to=(url_for("case_data.add"), "Back to data entry")), 500

templates/CaseDataEntry/add.html
{% extends "base.html" %}
{% block title %}
Add new entry
{% endblock %}

{% block content %}
    <h1>Add new data entry</h1>
    <form method="post" >
        <div class="form-group">
            <label>
                Date
                <input name="date" class="form-control" type="date" value="{{ now.date() }}" required/>
            </label>
            <label>
                Time
                <input name="time" class="form-control" type="time" value="{{ now.strftime('%H:%M') }}" required/>
            </label>
        </div>
        <div class="form-group">
            <label>
                Cases Region
                <input name="cases_reg" class="form-control" type="number" value="" min=0 required/>
            </label>
        </div>
        <div class="form-group">
            <label>
                Cases City
                <input name="cases_city" class="form-control" type="number" value="" min=0 required/>
            </label>
        </div>
        <div class="form-group">
            <label>
                Deaths
                <input name="deceased" class="form-control" type="number" value="" min=0 required/>
            </label>
        </div>
        <div class="form-group">
            <label>
                Recovered
                <input name="recovered" class="form-control" type="number" value=0 min=0 />
            </label>
        </div>
        <input class="btn btn-primary form-inline" type="submit" value="add" />
    </form>
{% endblock %}

templates/CaseDataEntry/add_csv.html
{% extends "base.html" %}

{% block title %}Add by CSV{% endblock%}
{% block content %}
    <h1>Add new data entry</h1>
    <form method="post" enctype="multipart/form-data">
        <div class="form-group">
            <label>
                File
                <input name="file" class="form-control" type="file" required/>
            </label>
        </div>
        <input class="btn btn-info form-control" type="submit" value="add" />
    </form>
{% endblock %}

templates/CaseDataEntry/add_from_external_page.html
{% extends "base.html" %}

{% block title %}
    Adding Cases from external source
{% endblock %}

{% block content %}
    <h1>Add case data from external source</h1>
    <h2>Found data:</h2>
    The following data was found:
    <div class="data">
        {% for case in data %}
            <form target="_blank" method="post" action="{{ url_for("case_data.add") }}">
                <div class="form-row justify-content-between" style="margin-left: 0; margin-right: 0">
                    <label for="date">
                        Date
                        <input name="date" class="form-control" type="date" required
                                {% if case["timestamp"] %}
                               value="{{ case["timestamp"].date() }}"
                                {% endif %}/>
                    </label>
                    <label for="time">
                        Time
                        <input name="time" class="form-control" type="time" required
                                {% if case["timestamp"] %}
                               value="{{ case["timestamp"].strftime('%H:%M') }}"
                                {% endif %}
                        />
                    </label>
                    <label>
                        Cases Region
                        <input name="cases_reg" class="form-control" type="number"
                               min=0 required
                                {% if case["cases_region"] %}
                               value="{{ case["cases_region"] }}"
                                {% endif %}/>
                    </label>
                    <label>
                        Cases City
                        <input name="cases_city" class="form-control" type="number"
                               min=0 required
                                {% if case["cases_city"] %}
                               value="{{ case["cases_city"] }}"
                                {% endif %}/>
                    </label>
                    <label>
                        Deaths
                        <input name="deceased" class="form-control" type="number" min=0
                               required
                                {% if case["deaths"] %}
                               value="{{ case["deaths"] }}"
                                {% endif %}/>
                    </label>
                    <label>
                        Recovered
                        <input name="recovered" class="form-control" type="number" min=0
                               required
                                {% if case["recovered"] %}
                               value="{{ case["recovered"] }}"
                                {% endif %}/>
                    </label>
                    <label>
                        Alsdorf
                        <input name="alsdorf" class="form-control" type="number" min=0
                               required
                                {% if case["alsdorf"] %}
                               value="{{ case["alsdorf"] }}"
                                {% endif %}/>
                    </label>
                    <label>
                        Baesweiler
                        <input name="baesweiler" class="form-control" type="number" min=0
                               required
                                {% if case["baesweiler"] %}
                               value="{{ case["baesweiler"] }}"
                                {% endif %}/>
                    </label>
                    <label>
                        Eschweiler
                        <input name="eschweiler" class="form-control" type="number" min=0
                               required
                                {% if case["eschweiler"] %}
                               value="{{ case["eschweiler"] }}"
                                {% endif %}/>
                    </label>
                    <label>
                        Herzogenrath
                        <input name="herzogenrath" class="form-control" type="number" min=0
                               required
                                {% if case["herzogenrath"] %}
                               value="{{ case["herzogenrath"] }}"
                                {% endif %}/>
                    </label>
                    <label>
                        Monschau
                        <input name="monschau" class="form-control" type="number" min=0
                               required
                                {% if case["monschau"] %}
                               value="{{ case["monschau"] }}"
                                {% endif %}/>
                    </label>
                    <label>
                        roetgen
                        <input name="roetgen" class="form-control" type="number" min=0
                               required
                                {% if case["roetgen"] %}
                               value="{{ case["roetgen"] }}"
                                {% endif %}/>
                    </label>
                    <label>
                        simmerath
                        <input name="simmerath" class="form-control" type="number" min=0
                               required
                                {% if case["simmerath"] %}
                               value="{{ case["simmerath"] }}"
                                {% endif %}/>
                    </label>
                    <label>
                        stolberg
                        <input name="stolberg" class="form-control" type="number" min=0
                               required
                                {% if case["stolberg"] %}
                               value="{{ case["stolberg"] }}"
                                {% endif %}/>
                    </label>
                    <label>
                        wuerselen
                        <input name="wuerselen" class="form-control" type="number" min=0
                               required
                                {% if case["wuerselen"] %}
                               value="{{ case["wuerselen"] }}"
                                {% endif %}/>
                    </label>
                    <label>
                        not located
                        <input name="not_associated" class="form-control" type="number" min=0
                               required
                                {% if case["not_associated"] %}
                               value="{{ case["not_associated"] }}"
                                {% endif %}/>
                    </label>
                    <label for="submit">
                        &nbsp;
                        <button name="submit" class="btn btn-primary form-control" type="submit">add</button>
                    </label>
                </div>
            </form>
            Extracted from:
            <div class="text-muted">{{ case["orig_date_str"] }}: {{ case["orig_data_str"] }}</div>
            <hr>
        {% endfor %}
    </div>
{% endblock %}

templates/CaseDataEntry/add_via_text.html
{% extends "base.html" %}

{% block title %}
    Adding Cases from external source
{% endblock %}

{% block content %}
    <h1>Add case data from text</h1>
    <div class="data">
        <form target="_blank" method="post" class="form" action="{{ url_for("case_data.fetch_via_text") }}">
            <div class="form-group justify-content-between" style="margin-left: 0; margin-right: 0">
                <label for="text">
                    Text
                    
                </label>
                <textarea name="text" class="form-control" rows="20" required ></textarea>
            </div>
            
            <button name="submit" class="btn btn-primary form-control" type="submit">add</button>
        </form>
    </div>
{% endblock %}

templates/CaseDataEntry/index.html
{% extends "base.html" %}

{% block title %}All Entries{% endblock %}

{% block content %}
    {% include "CaseDataEntry/common/table.html" %}
{% endblock %}